### PR TITLE
Loosen requirement versions

### LINKED ISSUE #223: Very restrictive version pinning
I understand that some people prefer an extreme version pinning of specific versions but that makes installing and packaging a nightmare. Specially when the package depends on some external libraries like `gdal` (via `rasterio`). It would be nice to get this reviewed and properly pinned only to the versions that are really needed due to API changes.

```
usgs==0.1.9
requests==2.7.0
python-dateutil==2.5.1
numpy==1.10.4
termcolor==1.1.0
rasterio==0.32.0
six>=1.8.0
scipy==0.17.0
scikit-image==0.12.3
homura==0.1.3
boto==2.39.0
polyline==1.3
geocoder==1.9.0
matplotlib==1.5.1
```

### PR DESCRIPTION
**Pull request by astrojuanlu**
I essentially widened the allowed versions for all dependencies, taking care of specifying `rasterio<1`. The current setup has been tested in all Python >= 3.4 versions (see commit logs). I also updated the Dockerfile, hopefully fixing another issue.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
(Issue links won't work in titles, so I hope this fixes #223).

**Comment by matthewhanson** [comment]
Thanks @Juanlu001 I think this would resolve #223, but I'm not sure it's such a good idea to use the minimum version syntax (>=) as it means that any major release for any of these packages (other than rasterio which you have specified) could break the install. The compatible release syntax (~=) I think might be preferable, e.g.

package~=1.1
is the same as saying >= 1.1. ==1.*

in the case of all these packages it doesn't make a difference right now, but could prevent a problem in the future. 

I've built and run the new Docker file you included and things seem to work fine. I'm happy to go ahead and merge this but I'd like to give a chance to @ocefpaf to provide any feedback on how this addresses his concerns. 

Also @drewbo @scisco if you have any strong feelings on version pinning please weight in.

Thanks again for the PR!

**Comment by ocefpaf** [comment]
>  I'd like to give a chance to @ocefpaf to provide any feedback on how this addresses his concerns.

LGTM. Thanks @Juanlu001 and @matthewhanson. This will make it much easier to build `landsat-util`.

**Comment by astrojuanlu** [comment]
Before you rush and merge this, I'm actually OK with using compatible release markers. I will assume though that, if it worked with `>=`, it will work with `~=` :)

**Comment by astrojuanlu** [comment]
...on second thought: I think this deserves some testing still, but I won't be able to do it next week.

**Comment by astrojuanlu** [comment]
I update the version requirements using `~=` or putting explicit upper bounds where appropriate. I tested again with the official Python Docker images and everything seemed to work, so from my side this is ready to merge.

**Comment by waqarmalik** [comment]
What's the status on this?

**Comment by astrojuanlu** [comment]
Ready to merge!

**Comment by astrojuanlu** [comment]
By the way, would it be possible to have a release with this changes? (A v0.14.0 I guess)

**Comment by guillochon** [comment]
Yes, can we please release this? The current version on pypi completely mucks with my Python stack.

**Pull request merged**
