### PR TITLE
Add street address search

### PR DESCRIPTION
**Pull request by mileswwatkins**
I noticed that it was on [the to-do list](https://github.com/developmentseed/landsat-util/blob/master/docs/todo.rst), and thought it'd be a nice feature to include.

I took a guess as to how you might like to handle imprecise geocoding, but let me know if you'd like me to tweak that `Exception` or any other piece.

### CODE REVIEW

**Comment by mileswwatkins** [comment]
Hmm, looks like Travis hit a bunch of unrelated bugs in `tests.test_image.TestProcess` that didn't pop up for me locally.

**Comment by scisco** [comment]
Will reopen if the PR is updated to pass tests

**Comment by mileswwatkins** [comment]
The tests pass locally for me; I think the `push` CI test isn't passing because my PR's coming from an external (forked) repo instead of the main `developmentseed` repo.

**Comment by scisco** [comment]
Moving this to #125

**Pull request closed without merging**
