### PR TITLE
Add capacity for NDVI output

### PR DESCRIPTION
**Pull request by willemarcel**

### CODE REVIEW

**Comment by scisco** [comment]
This has to be reimplemented in the future version of landsat with pure Python. On our to-do list.

**Comment by martinnormark** [comment]
@scisco Pure Python?

No use of GDAL or rasterio, or what do you mean by that?

**Comment by scisco** [comment]
@martinnormark Your are right. It's not exactly pure python. It heavily uses Rasterio which is written in python but also uses GDAL drivers. Other non-python dependencies such as orfeo and ImageMagick are dropped.

**Comment by martinnormark** [comment]
Alright. How far is that up on your to-do list?

**Comment by scisco** [comment]
Already released: https://github.com/developmentseed/landsat-util/releases/tag/v0.5.0

**Comment by martinnormark** [comment]
But does that include NDVI calculation?

**Pull request closed without merging**
