### PR TITLE
Update README formatting and add details on AWS.

### PR DESCRIPTION
**Pull request by jacquestardie**
Attempted to update the documentation a little.

Liberally reshuffled text and changed words.
Added details on saving to S3
Increased use of code blocks.
If there's anything else you'd like to see added let me know! :cake:

### CODE REVIEW

**Comment by jacquestardie** [comment]
Now that docs are up on ReadTheDocs, going to drop this.

**Comment by scisco** [comment]
@jacquestardie sorry I couldn't merge this. Could you apply your changes to the `docs` folder after I release v0.7.0?

**Comment by jacquestardie** [comment]
Sure thing!

**Comment by scisco** [comment]
Will reopen if new changes are submitted

**Pull request closed without merging**
