### PR TITLE
Fix process command documentation

### PR DESCRIPTION
**Pull request by llimllib**
The -p argument is not accepted by the `process` subcommand, so remove it from command documentation.

I'd also be happy to modify the `process` subcommand to accept -p if you'd prefer.

### CODE REVIEW

**Comment by JorgeGT** [comment]
I'd much prefer to maintain the doc as it is and add the '-p' argument to line 135: 
```python
parser_process.add_argument('-p', '--pansharpen', action='store_true',
```
So it is consistent with the rest of abbreviated commands like `-b` and `-v` (and we get to write less! :D)

**Comment by llimllib** [comment]
I added -p as an alias for pansharpen, and a test for same

**Comment by llimllib** [comment]
ping?

**Comment by scisco** [comment]
@llimllib sorry for the late response and thanks for your contribution. We have a develop branch that is considerably ahead of the master. Could you open a new PR to the develop branch?

We certainly need a contribution guideline to be clear about our dev process. We will add one very soon.

**Comment by llimllib** [comment]
np, will do

**Comment by llimllib** [comment]
the `develop` branch has already removed documentation for `-p`, that's good enough for me.

**Pull request closed without merging**
